version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covidproject"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xmwnev0fo1nr"
s3_prefix = "covidproject"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
